trigger:
  batch: true
  branches:
    include: 
    - main
  paths:
    include:
    - infra/*

parameters:
  - name: includeProduction
    type: boolean
  - name: location
    type: string
    default: canadacentral
  - name: devSubscriptionID
    type: string
    default: eda4c741-e019-47be-94a2-a64127c900c2
  - name: prdSubscriptionID
    type: string
    default: 64cad722-3e9f-46cb-b3b5-70689d59586a

variables:
  - name: devServiceConnection
    value: m3demos_dev
  - name: prdServiceConnection
    value: m3demos_prd
  - name: devSeedkeyvault
    value: m3diacwshpinfrakvt1d
  - name: prdSeedkeyvault
    value: m3diacwshpinfrakvt1p


stages:

  - stage: Validate_Bicep
    displayName: Validate Bicep
    jobs:
    - job: ValidateBicepCodeDEV
      displayName: Validate Bicep Code for DEV
      steps:
        - task: AzureResourceManagerTemplateDeployment@3
          name: RunPreflightValidation
          displayName: Run preflight validation
          inputs:
            connectedServiceName: ${{variables.devServiceConnection}}
            location: ${{parameters.location}}
            deploymentMode: Validation
            deploymentScope: Subscription
            subscriptionId: ${{parameters.devSubscriptionID}}
            csmFile: infra/demo1.bicep
            csmParametersFile: infra/demo1.dev.parameters.json
            overrideParameters: >
              -location ${{parameters.location}}

    - job: RunWhatIfDEV
      displayName: Run WhatIf in DEV
      steps:
      - task: AzureCLI@2
        displayName: 'Validate BICEP with What-If'
        inputs:
          azureSubscription: ${{variables.devServiceConnection}}
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment sub what-if \
              --location $(location) \
              --template-file $(Build.SourcesDirectory)/demo1.bicep \
              --parameters @$(Build.SourcesDirectory)/demo1.dev.parameters.json \
              --parameters vmPassword='placeholder' \
              --parameters sqlPassword= 'placeholder'

    - job: ValidateBicepCodePRD
      displayName: Validate Bicep Code for PRD
      steps:
        - task: AzureResourceManagerTemplateDeployment@3
          name: RunPreflightValidation
          displayName: Run preflight validation
          inputs:
            connectedServiceName: ${{variables.prdServiceConnection}}
            location: ${{parameters.location}}
            deploymentMode: Validation
            deploymentScope: Subscription
            subscriptionId: ${{parameters.prdSubscriptionID}}
            csmFile: infra/demo1.bicep
            csmParametersFile: infra/demo1.prd.parameters.json
            overrideParameters: >
              -parameter1 value1

    - job: RunWhatIfPRD
      displayName: Run WhatIf in PRD
      steps:
      - task: AzureCLI@2
        displayName: 'Validate BICEP with What-If'
        inputs:
          azureSubscription: ${{variables.prdServiceConnection}}
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment sub what-if \
              --location $(location) \
              --template-file $(Build.SourcesDirectory)/demo1.bicep \
              --parameters @$(Build.SourcesDirectory)/demo1.prd.parameters.json \
              --parameters vmPassword='placeholder' \
              --parameters sqlPassword= 'placeholder'

    - job: BuildAndPublishArtifact
      displayName: Build & Publish Bicep Artifact
      steps:
      - task: CopyFiles@2
        displayName: 'Include templates in the artifact'
        inputs:
          Contents: |
            infra/demo1.bicep
            infra/demo1.dev.parameters.json
            infra/demo1.prd.parameters.json
            infra/modules/*
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      
      - task: PublishBuildArtifacts@1
        displayName: 'Publish artifact'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'

  - stage: DeployToDEV
    dependsOn:
      Validate_Bicep
    condition: succeeded('Validate_Bicep')
    jobs:
      - deployment: DeployBICEP
        displayName: Deploy BICEP in DEV
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
              - task: DownloadBuildArtifacts@0
                displayName: 'Download artifact'
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'drop'
                  downloadPath: '$(System.ArtifactsDirectory)'
              
              - task: AzureKeyVault@2
                displayName: Get Keys from seed key vault
                inputs:
                  azureSubscription: ${{variables.prdServiceConnection}}
                  KeyVaultName: '${{variables.devSeedKeyvault}}'
                  SecretsFilter: '$(seedVMPassword), $(seedSQLPassword)'
                  RunAsPreJob: true
  
              - task: AzureCLI@2
                displayName: 'Deploy BICEP'
                inputs:
                  azureSubscription: ${{variables.devServiceConnection}}
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    az deployment sub create \
                      --location $(location) \
                      --template-file $(System.ArtifactsDirectory)/drop/demo1.bicep \
                      --parameters @$(System.ArtifactsDirectory)/drop/demo1.dev.parameters.json \
                      --parameters vmPassword='$(seedVMPassword)' \
                      --parameters sqlPassword='$(seedSQLPassword)'

  - stage: DeployToPRD
    dependsOn:
      Build_Validate
      DeployToDev
    condition: succeeded('DeployToDev')
    jobs:
      - deployment: DeployBICEP
        displayName: Deploy BICEP in PRD
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
              - task: DownloadBuildArtifacts@0
                displayName: 'Download artifact'
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'drop'
                  downloadPath: '$(System.ArtifactsDirectory)'
                  
              
              - task: AzureKeyVault@2
                displayName: Get Keys from seed key vault
                inputs:
                  azureSubscription: ${{variables.prdServiceConnection}}
                  KeyVaultName: '${{variables.prdSeedKeyvault}}'
                  SecretsFilter: '$(seedVMPassword), $(seedSQLPassword)'
                  RunAsPreJob: true
  
              - task: AzureCLI@2
                displayName: 'Deploy BICEP'
                inputs:
                  azureSubscription: ${{variables.prdServiceConnection}}
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    az deployment sub create \
                      --location $(location) \
                      --template-file $(System.ArtifactsDirectory)/drop/demo1.bicep \
                      --parameters @$(System.ArtifactsDirectory)/drop/demo1.prd.parameters.json \
                      --parameters vmPassword='$(seedVMPassword)' \
                      --parameters sqlPassword='$(seedSQLPassword)'